### ISSUE TITLE
Invoke-GHRestMethod

### ISSUE THREAD

**Issue by michelderooij** [damienvanrobaeys/Backup_Technet_Gallery_Contrib#1]
Hi Damien- your TN backup script calls Invoke-GHRestMethod, but I don't see a definition or reference to a required module

**Comment by damienvanrobaeys** [comment]
Hi Michel, if the migratetogithub switch has been selected a module will be automatically installed.
This one is called PowerShellforgithub.
I will publish about this module next week.

**Comment by michelderooij** [comment]
Ah, totally overlooked that section. Need coffee. Or glasses. Nice work, really helpful, saving lot of work for things I didn't put on GH yet :)

**Comment by damienvanrobaeys** [comment]
many thanks for the comment. You should try this module it's really awesome to play with github easily

**Comment by damienvanrobaeys** [comment]
may I close the issue ?
